name: "Build and Deploy"
on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * 5'

jobs:
  build-and-deploy-docker-image:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        name: Build and Deploy Image
        run: mvn -B clean install jib:build
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        name: Build and Deploy Tag Image
        run: mvn -B clean install jib:build -P release